import { motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, CirclePlay, Film, Instagram, Sparkles, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import WebGLArtScene from '../common/WebGLArtScene';
import { DemoBadge } from '../common/ArtistExperience';
import { useDemoCmsRows } from '../../lib/useDemoCms';

type PortfolioRow = { id: string; title: string; brand?: string; category?: string; thumbnail_url?: string; video_url?: string; status?: string; featured?: boolean };

const process = [
  ['01', 'FIND THE HOOK', 'The first second earns the next one.'],
  ['02', 'BUILD THE WORLD', 'Light, styling, camera and graphic language become one system.'],
  ['03', 'CUT FOR FEELING', 'Pace, sound and texture make the story land.'],
  ['04', 'SHIP WITH INTENT', 'Every reel has a purpose, not just a posting date.'],
];

const services = [
  { icon: Film, title: 'DIRECT THE REEL', copy: 'Concept, scripting, shoot direction and edit for vertical films that feel designed.', to: '/services' },
  { icon: Users, title: 'CAST THE CREATOR', copy: 'Influencer collaborations built around a strong product moment and a natural creator voice.', to: '/influencer-marketing' },
  { icon: Sparkles, title: 'BUILD THE FEED', copy: 'A social art direction system for campaigns, launches and recurring formats.', to: '/social-media-management' },
];

const concepts = [
  { title: 'AFTER DARK', kind: 'Fashion Launch', note: 'Flash / shadow / silhouette', bg: 'linear-gradient(150deg,#ff315f 0%,#7f234b 38%,#09090d 78%)' },
  { title: 'FIRST BITE', kind: 'Food Story', note: 'Sound before taste', bg: 'linear-gradient(150deg,#ffb05b 0%,#ff5a4e 38%,#27100d 78%)' },
  { title: 'TEXTURE', kind: 'Beauty Film', note: 'Light / liquid / skin', bg: 'linear-gradient(150deg,#cda7ff 0%,#ff7cb7 42%,#15101d 80%)' },
];

function FrameCorners() {
  return <><span className="absolute left-4 top-4 h-5 w-5 border-l border-t border-white/45" /><span className="absolute right-4 top-4 h-5 w-5 border-r border-t border-white/45" /><span className="absolute bottom-4 left-4 h-5 w-5 border-b border-l border-white/45" /><span className="absolute bottom-4 right-4 h-5 w-5 border-b border-r border-white/45" /></>;
}

function DirectorMonitor() {
  const reduceMotion = useReducedMotion();
  return (
    <motion.div initial={{ opacity: 0, y: 32, rotate: -2 }} animate={{ opacity: 1, y: 0, rotate: 0 }} transition={{ delay: .28, duration: .9, ease: [0.22, 1, 0.36, 1] }} className="director-monitor relative mx-auto aspect-[4/5] w-full max-w-[430px] overflow-hidden rounded-[30px] border border-white/12 bg-[#0a0b10] shadow-[0_50px_140px_rgba(0,0,0,.55)]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_68%_22%,rgba(255,90,140,.42),transparent_24%),linear-gradient(160deg,#16111a_0%,#601c46_38%,#13101b_65%,#07090f_100%)]" />
      <div className="absolute inset-0 cinematic-grid opacity-[.15]" />
      <motion.div aria-hidden="true" className="absolute -right-20 top-[15%] h-64 w-64 rounded-full border border-white/20" animate={reduceMotion ? undefined : { rotate: 360 }} transition={{ duration: 20, repeat: Infinity, ease: 'linear' }} />
      <motion.div aria-hidden="true" className="absolute left-[11%] top-[38%] h-32 w-32 rounded-[34px] border border-white/14 bg-white/[.08] backdrop-blur-xl" animate={reduceMotion ? undefined : { y: [0, -18, 0], x: [0, 8, 0], rotate: [-7, 6, -7] }} transition={{ duration: 6.5, repeat: Infinity, ease: 'easeInOut' }} />
      <FrameCorners />
      <div className="absolute left-6 right-6 top-6 flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold tracking-[.24em] text-white/45">CAM A / R2R</p><p className="mt-1 text-[10px] font-semibold tracking-[.14em] text-[#ff78ad]">REC ● 00:12:08</p></div><div className="rounded-full border border-white/12 bg-black/20 px-3 py-1.5 text-[9px] font-semibold tracking-[.18em] text-white/60 backdrop-blur-xl">DIRECTOR MODE</div></div>
      <div className="absolute inset-x-7 bottom-7"><p className="text-[9px] font-bold tracking-[.2em] text-white/42">SCENE 01 / ATTENTION</p><h2 className="mt-3 max-w-[7ch] font-[family-name:var(--font-display)] text-5xl font-bold leading-[.82] tracking-[-.06em] sm:text-6xl">MAKE THEM FEEL IT.</h2><div className="mt-5 grid grid-cols-[auto_1fr] items-center gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-full border border-white/16 bg-white/[.06]"><CirclePlay size={18} /></span><div className="flex gap-1.5">{[38,72,52,88,64,78,46].map((height,index)=><motion.span key={`${height}-${index}`} className="h-1 flex-1 rounded-full bg-white/20" animate={reduceMotion ? undefined : { scaleX: [.35,1,.35], opacity: [.3,1,.3] }} transition={{ duration: 1.6 + index*.12, repeat: Infinity, delay: index*.07 }} />)}</div></div></div>
      <div className="absolute inset-0 reel-scanline" />
    </motion.div>
  );
}

function PublishedWork({ items }: { items: PortfolioRow[] }) {
  if (!items.length) return null;
  return <section className="relative overflow-hidden bg-[#0b0c11] px-4 py-20 sm:px-6 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-7 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-[10px] font-bold tracking-[.28em] text-[#ff6aa7]">LIVE WORK / FROM CMS</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-5xl font-bold leading-[.86] tracking-[-.055em] sm:text-7xl">REAL WORK.<br />FRONT ROW.</h2></div><p className="max-w-xl text-sm leading-7 text-white/50 sm:text-base">Published work from the browser CMS takes priority over presentation concepts, so the site grows with the client.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{items.slice(0,3).map((item,index)=><motion.article key={item.id} initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}} className="group overflow-hidden rounded-[26px] border border-white/8 bg-white/[.025]"><div className="relative aspect-[4/5] overflow-hidden bg-[#11131a]">{item.video_url ? <video src={item.video_url} poster={item.thumbnail_url || undefined} muted loop playsInline autoPlay preload="metadata" className="h-full w-full object-cover" /> : item.thumbnail_url ? <img src={item.thumbnail_url} alt={item.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.04]" /> : <div className="absolute inset-0 bg-[linear-gradient(155deg,#ff4d73,#76224e_45%,#0a0b10)]" />}<div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-transparent" /><div className="absolute inset-x-5 bottom-5"><p className="text-[9px] font-bold tracking-[.18em] text-[#ff78ad]">{item.category || 'PUBLISHED WORK'}</p><h3 className="mt-2 font-[family-name:var(--font-display)] text-2xl font-bold">{item.title}</h3>{item.brand && <p className="mt-1 text-xs text-white/45">{item.brand}</p>}</div></div></motion.article>)}</div></div></section>;
}

export default function DirectorCutHome() {
  const reduceMotion = useReducedMotion();
  const { rows: cmsWork } = useDemoCmsRows<PortfolioRow>('portfolio_items');
  const publishedWork = cmsWork.filter((item) => item.status !== 'draft');
  return (
    <div className="director-home relative overflow-hidden bg-[#07090f] text-white">
      <section className="relative min-h-[100svh] overflow-hidden border-b border-white/[.06]">
        <div className="absolute inset-0"><WebGLArtScene variant="hero" className="h-full w-full opacity-[.5]" /><div className="absolute inset-0 bg-[linear-gradient(90deg,#07090f_0%,rgba(7,9,15,.96)_38%,rgba(7,9,15,.6)_62%,rgba(7,9,15,.24)_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,#07090f_0%,transparent_24%,transparent_70%,rgba(7,9,15,.84)_100%)]" /></div>
        <div className="relative mx-auto grid min-h-[100svh] max-w-7xl items-center gap-10 px-4 pb-24 pt-28 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:px-8 lg:pb-12 lg:pt-24">
          <div className="relative z-10 min-w-0"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="flex flex-wrap items-center gap-3"><span className="rounded-full border border-white/12 bg-black/25 px-4 py-2 text-[9px] font-bold tracking-[.24em] text-white/68 backdrop-blur-xl">REEL2REACH / CREATIVE DIRECTION</span><span className="text-[9px] font-bold tracking-[.22em] text-[#ff6aa7]">SOCIAL FILMS / CREATOR CULTURE</span></motion.div><div className="mt-8"><div className="overflow-hidden pb-1"><motion.h1 initial={{y:'110%'}} animate={{y:0}} transition={{duration:.9,ease:[.22,1,.36,1]}} className="font-[family-name:var(--font-display)] text-[18vw] font-bold leading-[.76] tracking-[-.07em] sm:text-[7.9rem] lg:text-[8rem] xl:text-[9.2rem]">REEL</motion.h1></div><div className="overflow-hidden pb-1"><motion.h1 initial={{y:'110%'}} animate={{y:0}} transition={{duration:.9,delay:.08,ease:[.22,1,.36,1]}} className="font-[family-name:var(--font-display)] text-[18vw] font-bold leading-[.76] tracking-[-.07em] sm:text-[7.9rem] lg:text-[8rem] xl:text-[9.2rem]">TO</motion.h1></div><div className="overflow-hidden pb-2"><motion.h1 initial={{y:'110%'}} animate={{y:0}} transition={{duration:.95,delay:.16,ease:[.22,1,.36,1]}} className="director-outline font-[family-name:var(--font-display)] text-[18vw] font-bold leading-[.76] tracking-[-.07em] sm:text-[7.9rem] lg:text-[8rem] xl:text-[9.2rem]">REACH</motion.h1></div></div><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.45}} className="mt-7 grid max-w-2xl gap-6 sm:grid-cols-[1fr_auto] sm:items-end"><p className="max-w-lg text-sm leading-7 text-white/58 sm:text-base">We turn products, people and ideas into social films with a point of view — concept, direction, creators, edit and rollout.</p><p className="text-[9px] font-bold uppercase tracking-[.2em] text-white/28 sm:text-right">Your brand.<br />Our reel.<br />Everyone sees it.</p></motion.div><motion.div initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:.58}} className="mt-8 flex flex-col gap-3 min-[430px]:flex-row"><Link to="/portfolio" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-[#07090f] transition hover:-translate-y-0.5">VIEW THE WORK <CirclePlay size={16} /></Link><Link to="/book" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-full border border-white/16 bg-black/25 px-6 py-3.5 text-sm font-semibold backdrop-blur-xl transition hover:border-white/32 hover:bg-white/[.06]">START A PROJECT <ArrowRight size={16} /></Link></motion.div></div>
          <div className="relative z-10 hidden lg:block"><DirectorMonitor /></div>
        </div>
        <div className="relative z-10 mx-auto -mt-12 block max-w-sm px-5 pb-24 lg:hidden"><DirectorMonitor /></div>
        <div className="absolute bottom-0 left-0 right-0 overflow-hidden border-t border-white/[.06] bg-black/25 py-3 backdrop-blur-md"><div className="artist-marquee flex w-max whitespace-nowrap text-[9px] font-bold tracking-[.22em] text-white/30">{[...Array(3)].flatMap(()=>['DIRECTION','REELS','CREATORS','EDIT','SOCIAL','STORY']).map((word,index)=><span key={`${word}-${index}`} className="mx-7">{word}<span className="ml-7 text-[#ff3d8d]/55">✦</span></span>)}</div></div>
      </section>
      <section className="relative overflow-hidden bg-[#efe9df] px-4 py-20 text-[#0a0a0d] sm:px-6 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="text-[10px] font-bold tracking-[.26em] text-black/38">THE CREATIVE RULE</p><p className="mt-5 max-w-sm text-sm leading-7 text-black/56">Don’t decorate content after the fact. Decide what it should feel like before the camera starts.</p></div><motion.h2 initial={{opacity:0,y:36}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="font-[family-name:var(--font-display)] text-[14vw] font-bold leading-[.78] tracking-[-.065em] sm:text-[6.8rem] lg:text-[8rem]">WE DON’T<br />CHASE<br /><span className="text-[#ff315f]">TRENDS.</span><br />WE FRAME<br />ATTENTION.</motion.h2></div></div></section>
      <section className="relative overflow-hidden bg-[#090a0f] px-4 py-20 sm:px-6 lg:px-8 lg:py-32"><div className="pointer-events-none absolute inset-0 cinematic-grid opacity-[.07]" /><div className="relative mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.78fr_1.22fr] lg:items-end"><div><p className="text-[10px] font-bold tracking-[.28em] text-[#ff6aa7]">THE R2R METHOD</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-5xl font-bold leading-[.88] tracking-[-.055em] sm:text-7xl">FROM<br />HOOK TO<br />MEMORY.</h2></div><p className="max-w-xl text-sm leading-7 text-white/50 sm:text-base">A simple creative system that keeps the idea stronger than the effects.</p></div><div className="mt-12 grid border-y border-white/8 md:grid-cols-2 lg:grid-cols-4">{process.map(([n,title,copy],index)=><motion.div key={n} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}} className="relative border-b border-white/8 p-6 md:border-r lg:border-b-0 lg:p-7 last:border-r-0"><p className="text-[10px] font-bold tracking-[.2em] text-white/26">{n}</p><h3 className="mt-10 font-[family-name:var(--font-display)] text-2xl font-bold leading-[.95] tracking-[-.04em]">{title}</h3><p className="mt-4 text-sm leading-6 text-white/45">{copy}</p></motion.div>)}</div></div></section>
      <section className="bg-[#07090f] px-4 py-20 sm:px-6 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 border-b border-white/8 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold tracking-[.28em] text-[#ff6aa7]">THREE CREATIVE ENGINES</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-5xl font-bold leading-[.9] tracking-[-.05em] sm:text-7xl">WHAT WE<br />DIRECT.</h2></div><Link to="/services" className="inline-flex items-center gap-2 text-sm font-semibold text-white/65 transition hover:text-white">ALL SERVICES <ArrowUpRight size={16} /></Link></div><div>{services.map((service,index)=><motion.div key={service.title} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}}><Link to={service.to} className="group grid gap-5 border-b border-white/8 py-8 sm:grid-cols-[72px_1fr_1fr_auto] sm:items-center sm:px-3 lg:py-10"><span className="font-[family-name:var(--font-display)] text-4xl font-bold text-white/[.08]">0{index+1}</span><div className="flex items-center gap-4"><service.icon size={20} className="text-[#ff6aa7]" /><h3 className="font-[family-name:var(--font-display)] text-2xl font-bold sm:text-3xl">{service.title}</h3></div><p className="text-sm leading-6 text-white/46">{service.copy}</p><ArrowUpRight size={20} className="transition duration-300 group-hover:-translate-y-1 group-hover:translate-x-1" /></Link></motion.div>)}</div></div></section>
      <PublishedWork items={publishedWork} />
      <section className="relative overflow-hidden bg-[#0b0d14] px-4 py-20 sm:px-6 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[10px] font-bold tracking-[.28em] text-[#ff6aa7]">CONCEPT LAB / SPEC WORK</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-5xl font-bold leading-[.88] tracking-[-.055em] sm:text-7xl">THREE MOODS.<br />THREE WORLDS.</h2></div><p className="max-w-sm text-xs leading-6 text-white/40">Clearly labelled presentation concepts. No fake client claims, no fake results.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{concepts.map((item,index)=><motion.article key={item.title} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.07}} className="group relative min-h-[460px] overflow-hidden rounded-[28px] border border-white/9" style={{background:item.bg}}><div className="absolute inset-0 cinematic-grid opacity-[.15]" /><motion.div aria-hidden="true" className="absolute -right-16 top-12 h-56 w-56 rounded-full border border-white/20" animate={reduceMotion ? undefined : {rotate:[0,28,0],scale:[1,1.08,1]}} transition={{duration:9+index,repeat:Infinity,ease:'easeInOut'}} /><div className="absolute left-5 top-5"><DemoBadge label="DEMO / SPEC CONCEPT" /></div><div className="absolute inset-x-6 bottom-6"><p className="text-[9px] font-bold tracking-[.2em] text-white/55">{item.kind.toUpperCase()}</p><h3 className="mt-3 font-[family-name:var(--font-display)] text-4xl font-bold tracking-[-.05em] sm:text-5xl">{item.title}</h3><p className="mt-3 text-sm font-semibold tracking-[.08em] text-white/65">{item.note}</p></div></motion.article>)}</div><div className="mt-8 flex justify-end"><Link to="/portfolio" className="inline-flex items-center gap-2 text-sm font-semibold text-white/65 transition hover:text-white">OPEN THE FULL WORKBOOK <ArrowRight size={16} /></Link></div></div></section>
      <section className="relative overflow-hidden bg-[#ff3d8d] px-4 py-20 text-[#09090d] sm:px-6 lg:px-8 lg:py-28"><motion.div aria-hidden="true" className="absolute -right-20 -top-24 h-80 w-80 rounded-full border border-black/10" animate={reduceMotion ? undefined : {rotate:360}} transition={{duration:28,repeat:Infinity,ease:'linear'}} /><div className="relative mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="text-[10px] font-bold tracking-[.28em] text-black/48">NEXT SCENE?</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-[14vw] font-bold leading-[.78] tracking-[-.065em] sm:text-[6.8rem] lg:text-[8.2rem]">YOUR<br />BRAND.</h2></div><div className="lg:pb-3"><p className="max-w-md text-sm leading-7 text-black/65 sm:text-base">Bring the product. Bring the brief. We’ll build the visual language around it.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link to="/book" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-full bg-[#09090d] px-6 py-3.5 text-sm font-bold text-white">BOOK A COLLAB <ArrowRight size={16} /></Link><a href="https://instagram.com/ashwini_rathod_19" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-full border border-black/20 px-6 py-3.5 text-sm font-bold"><Instagram size={16} /> INSTAGRAM</a></div></div></div></section>
    </div>
  );
}
